/* ----------------------------------------------------------------------- *\
|
|	ASCII.H   Include file for the ASCII character set
|
\* ----------------------------------------------------------------------- */

/* ASCII character definitions */

#ifndef	NUL
#define NUL	0x00
#endif
#ifndef	SOH
#define SOH	0x01
#endif
#ifndef	STX
#define STX	0x02
#endif
#ifndef	ETX
#define ETX	0x03
#endif
#ifndef	EOT
#define EOT	0x04
#endif
#ifndef	ENQ
#define ENQ	0x05
#endif
#ifndef	ACK
#define ACK	0x06
#endif
#ifndef	BEL
#define BEL	0x07
#endif
#ifndef	BS	
#define BS	0x08
#endif
#ifndef	HT	
#define HT	0x09
#endif
#ifndef	LF	
#define LF	0x0A
#endif
#ifndef	VT	
#define VT	0x0B
#endif
#ifndef	FF	
#define FF	0x0C
#endif
#ifndef	CR	
#define CR	0x0D
#endif
#ifndef	SO	
#define SO	0x0E
#endif
#ifndef	SI	
#define SI	0x0F
#endif

/* ----------------------------------------------------------------------- */

/* ----------------------------------------------------------------------- */

/* ASCII character definitions CONTINUED */

#ifndef	DLE
#define DLE	0x10
#endif
#ifndef	DC1
#define DC1	0x11
#endif
#ifndef	DC2
#define DC2	0x12
#endif
#ifndef	DC3
#define DC3	0x13
#endif
#ifndef	DC4
#define DC4	0x14
#endif
#ifndef	NAK
#define NAK	0x15
#endif
#ifndef	SYN
#define SYN	0x16
#endif
#ifndef	ETB
#define ETB	0x17
#endif
#ifndef	CAN
#define CAN	0x18
#endif
#ifndef	EM	
#define EM	0x19
#endif
#ifndef	SUB
#define SUB	0x1A
#endif
#ifndef	ESC
#define ESC	0x1B
#endif
#ifndef	FS 
#define FS 	0x1C
#endif
#ifndef	GS 
#define GS 	0x1D
#endif
#ifndef	RS 
#define RS 	0x1E
#endif
#ifndef	VS 
#define VS 	0x1F
#endif
#ifndef	DEL
#define DEL	0x7F
#endif

/* ----------------------------------------------------------------------- */
